#!/bin/bash
# 云函数部署脚本
# 使用方法：在微信开发者工具中，点击顶部菜单"云开发" -> "云函数列表"，然后右键点击需要部署的云函数，选择"上传并部署"

echo "微信小程序云函数部署指南"
echo "=========================="
echo ""
echo "请按照以下步骤部署云函数和创建数据库集合："
echo ""
echo "1. 设置云环境："
echo "   - 在app.js中修改env参数为您的云环境ID"
echo "   - 打开微信开发者工具，点击左侧'云开发'按钮"
echo "   - 如果没有云环境，请点击'创建环境'"
echo ""
echo "2. 部署云函数："
echo "   - 在云开发控制台中，点击'云函数'"
echo "   - 将cloudfunctions目录下的所有函数上传到云端："
echo "     * getOrderList - 获取订单列表"
echo "     * getUserData - 获取用户数据"
echo "     * acceptOrder - 接受订单"
echo "     * createOrder - 创建订单"
echo "     * getConfig - 获取系统配置"
echo "     * completeOrder - 完成订单"
echo "     * cancelOrder - 取消订单"
echo "     * getOngoingOrders - 获取进行中的订单"
echo ""
echo "3. 创建数据库集合："
echo "   - 在云开发控制台中，点击'数据库'"
echo "   - 创建以下集合："
echo "     * orders - 订单信息"
echo "     * users - 用户信息"
echo "     * pointsHistory - 积分历史"
echo "     * config - 系统配置"
echo ""
echo "4. 设置云函数的环境变量："
echo "   - 对于每个云函数，可以设置环境变量，如："
echo "     * ENV_ID - 云环境ID"
echo ""
echo "完成以上步骤后，您的云开发环境就配置好了！"
echo ""
echo "注意："
echo "在开发环境中，您可以使用模拟登录功能进行测试。"
echo "请确保在发布前完成所有云函数的部署和数据库集合的创建。
